version: "3"
services:
    go-app:
        build:
            dockerfile: ./app/Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: exchanegdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: carvalho
        ports:
            - "5432:5432"
        volumes:
            - ./sql-scripts:/docker-entrypoint-initdb.d
