version: "3"
services:
    go-app:
        build:
            context: ./app
        ports:
            - "8080:8080"
        depends_on:
            - db
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: mydb
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        ports:
            - "5432:5432"
        volumes:
            - ./sql-scripts:/docker-entrypoint-initdb.d
